tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"

brew "ack"
brew "awscli"
brew "awslogs"
brew "node"
brew "bash-language-server"
brew "black"
brew "ccache"
brew "clang-format"
brew "cmake"
brew "curl"
brew "entr"
brew "exiftool"
brew "ffmpeg"
brew "fzf"
brew "imagemagick"
brew "jq"
brew "yt-dlp"
brew "mpv"
brew "neovim"
brew "newsboat"
brew "octave"
brew "php"
brew "plantuml"
brew "redis", restart_service: true
brew "sox"
brew "stylua"
brew "switchaudio-osx"
brew "terraform"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "zoxide"
brew "zsh-syntax-highlighting"
brew "hashicorp/tap/terraform-ls"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"

cask "aldente"
cask "authy"
cask "blackhole-2ch"
cask "blender"
cask "docker"
cask "dropbox"
cask "figma"
cask "font-sf-mono"
cask "github"
cask "iterm2"
cask "postman"
cask "rectangle"
cask "sequel-ace"
cask "skype"
cask "slack"
cask "spotify"
cask "transmission"
cask "webpquicklook"
cask "zoom"

mas "Adblock Plus", id: 1432731683
mas "Bitwarden", id: 1352778147
mas "Messenger", id: 1480068668
mas "MindNode", id: 1289197285
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "WhatsApp", id: 1147396723
